### ISSUE TITLE
asking about Linux

### ISSUE THREAD

**Issue by MohamedAbdElsalam10** [MohamedRadwan-DevOps/DevOps-step-by-step-arabic#35]
hi eng mohamed
i hope you are fine, i just wanted to ask why Linux is not in the prerequisites, i see Linux and bash scripting are a must tools in all 
devops roadmaps and recommendations, isn't Linux going to be used in the course ?

**Comment by RehabAbotalep** [comment]
@MohamedAbdElsalam10  We are already going to add (Bash Scripting - Power Shell ) to the prerequisites.
